### ISSUE TITLE
Geolocation version

### ISSUE THREAD

**Issue by sharonmleon** [CPHDH/Curatescape#48] opened 2016-07-21 18:37 UTC
Update the link to the current version of the Geolocation plugin (2.2.4) to account for the Google Console API Key requirement.

**Comment by sashafr** [comment] 2016-07-25 20:11
I am thinking my contribution form problem might be related to the lack of API key problem, but even after I upgraded to 2.2.4, my Contribution form is not showing the map. In fact, it won't even load the form (after selecting a type from the dropdown). I am showing this error every time I make a selection from the dropdown:

`Uncaught ReferenceError: OmekaMapForm is not defined`

This only occurs when "Add Map To Contribution Form" box is checked in Geolocation settings.

**Comment by ebellempire** [comment] 2016-07-25 20:25
It's important to note the way that Curatescape uses the Geolocation plugin. We really only use it to enter and store data. All the display stuff is custom and it's designed to work in a relatively narrow set of circumstances. This means there can sometimes be compatibility issues with unsupported plugins. Curatescape does not currently support the Contribution or Guest User plugins. It's possible to add support (e.g. as evidenced on [Smithsonian Community of Gardens](https://communityofgardens.si.edu/)) but it does require some coding and design. I'm not sure what exactly is going on with the map on the Contribution form, but the first thing I would try is to delete (or just move/rename) the folder at `/themes/curatescape/contribution` and see if it works. If so, the problem is in one of those templates, which were never finished and haven't been fully tested (I'm going to remove them now actually!). One other thing to look into is wether or not the Google Maps API and other required scripts are being loaded in the header (they probably are not, so you'd need to add those in when/if you create custom contribution templates).

**Comment by ebellempire** [comment] 2016-07-27 19:52
Done, thanks! 
https://github.com/CPHDH/Curatescape/commit/c133f769614bebb40167f09a19dc9d848e746479
https://github.com/CPHDH/Curatescape/commit/f8be8947f373ebc23e74c79f92726bb65ee8e196

**Closed by ebellempire** 2016-07-27 19:52 UTC
